name: SourceHan font ttf

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '^3.10.1'

      - name: Build
        run: |
          pip install otf2ttf

          # 思源宋体
          # 下载
          wget https://github.com/adobe-fonts/source-han-serif/releases/latest/download/SourceHanSerifSC.zip
          # 解压
          unzip SourceHanSerifSC.zip
          # 转换
          otf2ttf OTF/SimplifiedChinese/SourceHanSerifSC-Bold.otf
          # 获取版本
          version="$(curl --silent "https://api.github.com/repos/adobe-fonts/source-han-serif/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')"
          mkdir font
          mv OTF/SimplifiedChinese/*.ttf font
          # 压缩
          cd font
          zip -9 -r -UN=UTF8 ../SourceHanSerifSC_TTF_$version.zip *.ttf
          cd ${{ github.workspace }}
          # 清理
          rm -rf OTF font *.txt

          # 思源黑体
          wget https://github.com/adobe-fonts/source-han-sans/releases/latest/download/SourceHanSansSC.zip
          # 解压
          unzip SourceHanSansSC.zip
          # 转换
          otf2ttf OTF/SimplifiedChinese/SourceHanSansSC-Bold.otf
          # 获取版本
          version="$(curl --silent "https://api.github.com/repos/adobe-fonts/source-han-sans/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')"
          mkdir font
          mv OTF/SimplifiedChinese/*.ttf font
          # 压缩
          cd font
          zip -9 -r -UN=UTF8 ../SourceHanSansSC_TTF_$version.zip *.ttf
          cd ${{ github.workspace }}
          # 清理
          rm -rf OTF font *.txt

          echo "$(date +'%Y%m%d')" >> $GITHUB_ENV


      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          tag: ${{ env.DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
